site_name: Test docs
site_description: 'A docs test'
site_author: ''
docs_dir: docs/
repo_name: 'lensapp/lens'
repo_url: 'https://github.com/lensapp/lens'
nav:
    - Overview: index.md
    - Get Started:
        - Your First Extension: your_first_extension.md
theme:
  name: 'readthedocs'
