site_name: Documentation for Lens IDE
site_description: Documentation for Lens IDE. The only system you’ll ever need to take control of your Kubernetes clusters. It's open source and free. Download it today!
site_author: Mirantis, Inc.
site_url: https://docs.k8slens.dev
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/lensapp/lens
copyright: Copyright &copy; 2020 <a href="https://mirantis.com/">Mirantis Inc.</a> - All rights reserved.
edit_uri: ""
nav:
    - Overview: index.md
    - Setup: 
      - Overview: setup/overview.md
      - Linux: setup/linux.md
      - macOS: setup/macos.md
      - Windows: setup/windows.md
      - Network: setup/network.md
    - Extensions:
        - Overview: extensions/overview.md
        - Get Started: 
          - Your First Extension: extensions/get-started/your-first-extension.md
          - Extension Anatomy: extensions/get-started/your-first-extension.md
        - Extension Capabilities: 
          - Overview: extensions/get-started/your-first-extension.md
          - Common Capabilities:  extensions/get-started/your-first-extension.md
          - Theming: extensions/get-started/your-first-extension.md
        - Extension Guides:
          - Overview: extensions/get-started/your-first-extension.md
        - Testing and Publishing:
          - Testing Extensions: extensions/get-started/your-first-extension.md
          - Publishing Extensions: extensions/get-started/your-first-extension.md
          - Bundling Extensions: extensions/get-started/your-first-extension.md
theme:
  name: 'material'
  highlightjs: true
  language: 'en'
  custom_dir: custom_theme

extra_css:
  - css/extra.css
