site_name: Lens - The Kubernetes IDE Documentation
site_description: Documentation for Lens IDE. The only system you’ll ever need to take control of your Kubernetes clusters. It's open source and free. Download it today!
site_author: Mirantis, Inc.
site_url: https://docs.k8slens.dev
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/lensapp/lens
copyright: Copyright &copy; 2020 <a href="https://mirantis.com/">Mirantis Inc.</a> - All rights reserved.
edit_uri: ""
nav:
    - Overview: index.md
    - Setup: 
      - Overview: setup/overview.md
      - Linux: setup/linux.md
      - macOS: setup/macos.md
      - Windows: setup/windows.md
      - Network: setup/network.md
    - Extensions:
        - Overview: extensions/overview.md
        - Get Started: 
          - Your First Extension: extensions/get-started/your-first-extension.md
          - Extension Anatomy: extensions/get-started/anatomy.md
        - Extension Capabilities: 
          - Overview: extensions/capabilities/overview.md
          - Common Capabilities: extensions/capabilities/common-capabilities.md
          - Theming: extensions/capabilities/theming.md
        - Extension Guides:
          - Overview: extensions/guides/overview.md
        - Testing and Publishing:
          - Testing Extensions: extensions/testing-and-publishing/testing.md
          - Publishing Extensions: extensions/testing-and-publishing/publishing.md
          - Bundling Extensions: extensions/testing-and-publishing/bundling.md
theme:
  name: 'material'
  highlightjs: true
  language: 'en'
  custom_dir: docs/custom_theme
  favicon: img/favicon.ico
  logo: img/lens-logo-icon.svg
  palette:
    scheme: preference
  features:
    - navigation.instant

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 0

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lensapp/lens
      name: Lens on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/k8slens
      name: Lens on Twitter
    - icon: fontawesome/brands/slack
      link: http://k8slens.slack.com/
      name: Lens on Slack