name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - extensions-docs

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Release from lens
        uses: actions/checkout@v2

      - name: Checkout Branch "gh-pages" from "lensapp/docs"
        uses: actions/checkout@v2
        with:
          repository: lensapp/docs
          path: /lensdocs


      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
