name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - extensions-docs

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Release from lens
        uses: actions/checkout@v2

      - name: Checkout Branch "gh-pages" from "lensapp/docs"
        uses: actions/checkout@v2
        with:
          repository: lensapp/docs
          path: lensdocs

      - name: Set up Python 3.7 
        uses: actions/setup-python@v2 
        with: 
          python-version: '3.x' 
      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip 
          pip install mkdocs-material 
          
      - name: Build mkdocs
        run: | 
           mkdocs build
           cp -R site/*  ./lensdocs/.
           cd ./lensdocs/
           git commit -am "Build mkdocs from GH-Actions"
           git push
          
