name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - extensions-docs

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Release from lens
        uses: actions/checkout@v2
        with:
          repository: lensapp/lens
          path: lens

      # - name: Checkout lensapp/mkdocs-material-insiders
      #   uses: actions/checkout@v2
      #   with:
      #     repository: lensapp/mkdocs-material-insiders
      #     path: mkdocs-material-insiders
      #     token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python 3.7 
        uses: actions/setup-python@v2 
        with: 
          python-version: '3.x' 
      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip
          pip install git+https://${{ secrets.GH_TOKEN }}@github.com/lensapp/mkdocs-material-insiders.git
          pip install mkdocs-git-revision-date-localized-plugin mike
          
      - name: mkdocs deploy
        run: | 
           cd lens/
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           mike deploy --push --force --update-aliases 4.0.0 latest

           
#      - name: Commit files
#        run: |
#          cd lensdocs/
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git commit -am "Build mkdocs from GH-Actions"
          
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          directory: ./lensdocs
#          repository: lensapp/docs
#          branch: gh-pages
#          github_token: ${{ secrets.GH_TOKEN }}
          
